{ lib, ... }:
let
  # Convert "#rrggbb" hex to sketchybar's 0xAARRGGBB format
  toLuaColor = hex: alpha: "0x${alpha}${builtins.substring 1 6 hex}";

  # Tokyo Night Dark palette
  palette = {
    bg = "#1a1b26";
    bg_dark = "#16161e";
    bg_highlight = "#292e42";
    fg = "#c0caf5";
    fg_dim = "#a9b1d6";
    fg_gutter = "#3b4261";
    black = "#15161e";
    grey = "#414868";
    red = "#f7768e";
    green = "#9ece6a";
    yellow = "#e0af68";
    blue = "#7aa2f7";
    magenta = "#bb9af7";
    cyan = "#7dcfff";
    orange = "#ff9e64";
    purple = "#9d7cd8";
    teal = "#1abc9c";
    comment = "#565f89";
    blue0 = "#3d59a1";
    blue1 = "#2ac3de";
    blue2 = "#0db9d7";
  };

  c = name: toLuaColor palette.${name} "ff";

  colorsLua = ''
    -- GENERATED BY NIX - do not edit manually
    -- Theme: Tokyo Night Dark
    -- Edit hosts/m3-work-laptop/sketchybar-theme.nix to change colors

    return {
      with_alpha = function(color, alpha)
        return (color % 0x01000000) + (alpha * 0x01000000)
      end,

      transparent = 0x00000000,

      bar = {
        bg = ${toLuaColor palette.bg "88"},
        border = ${toLuaColor palette.fg_dim "44"},
      },

      popup = {
        bg = ${toLuaColor palette.bg_dark "ee"},
        border = ${toLuaColor palette.fg_gutter "ff"},
      },

      bg1 = ${c "bg"},
      bg2 = ${c "bg_dark"},
      bg3 = ${c "bg_highlight"},

      item_bg = ${toLuaColor palette.bg_highlight "cc"},
      widget_bg = ${toLuaColor palette.fg_gutter "dd"},

      fg = ${c "fg"},
      fg_dim = ${c "fg_dim"},
      fg_gutter = ${c "fg_gutter"},

      black = ${c "black"},
      grey = ${c "grey"},
      red = ${c "red"},
      green = ${c "green"},
      yellow = ${c "yellow"},
      blue = ${c "blue"},
      magenta = ${c "magenta"},
      cyan = ${c "cyan"},
      orange = ${c "orange"},
      purple = ${c "purple"},
      teal = ${c "teal"},
      comment = ${c "comment"},

      blue0 = ${c "blue0"},
      blue1 = ${c "blue1"},
      blue2 = ${c "blue2"},
    }
  '';

  wmConfigLua = ''
    -- GENERATED BY NIX - do not edit manually
    return {
      use_aerospace = true,
    }
  '';
in
{
  xdg.configFile = {
    "sketchybar/colors.lua" = {
      text = colorsLua;
    };
    "sketchybar/wm_config.lua" = {
      text = wmConfigLua;
    };
  };
}
